/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_DisparityTransformFilter */

#ifndef _Included_com_intel_realsense_librealsense_DisparityTransformFilter
#define _Included_com_intel_realsense_librealsense_DisparityTransformFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_DisparityTransformFilter
 * Method:    nCreate
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_DisparityTransformFilter_nCreate
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
