/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_PipelineProfile */

#ifndef _Included_com_intel_realsense_librealsense_PipelineProfile
#define _Included_com_intel_realsense_librealsense_PipelineProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_PipelineProfile
 * Method:    nDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_PipelineProfile_nDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_PipelineProfile
 * Method:    nGetDevice
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_PipelineProfile_nGetDevice
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
