/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_Points */

#ifndef _Included_com_intel_realsense_librealsense_Points
#define _Included_com_intel_realsense_librealsense_Points
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_Points
 * Method:    nGetCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_Points_nGetCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Points
 * Method:    nGetData
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Points_nGetData
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_intel_realsense_librealsense_Points
 * Method:    nGetTextureCoordinates
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Points_nGetTextureCoordinates
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_intel_realsense_librealsense_Points
 * Method:    nExportToPly
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Points_nExportToPly
  (JNIEnv *, jclass, jlong, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
