/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_FwLogger */

#ifndef _Included_com_intel_realsense_librealsense_FwLogger
#define _Included_com_intel_realsense_librealsense_FwLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_FwLogger
 * Method:    nGetFwLog
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FwLogger_nGetFwLog
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogger
 * Method:    nGetFlashLog
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FwLogger_nGetFlashLog
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogger
 * Method:    nGetNumberOfFwLogs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FwLogger_nGetNumberOfFwLogs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogger
 * Method:    nInitParser
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_realsense_librealsense_FwLogger_nInitParser
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_intel_realsense_librealsense_FwLogger
 * Method:    nParseFwLog
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FwLogger_nParseFwLog
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
