/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_FrameSet */

#ifndef _Included_com_intel_realsense_librealsense_FrameSet
#define _Included_com_intel_realsense_librealsense_FrameSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_FrameSet
 * Method:    nAddRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_FrameSet_nAddRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FrameSet
 * Method:    nRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_FrameSet_nRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FrameSet
 * Method:    nExtractFrame
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FrameSet_nExtractFrame
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_FrameSet
 * Method:    nFrameCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_FrameSet_nFrameCount
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
