/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_Pipeline */

#ifndef _Included_com_intel_realsense_librealsense_Pipeline
#define _Included_com_intel_realsense_librealsense_Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_Pipeline
 * Method:    nCreate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Pipeline_nCreate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Pipeline
 * Method:    nDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Pipeline_nDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Pipeline
 * Method:    nStart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Pipeline_nStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Pipeline
 * Method:    nStartWithCallback
 * Signature: (JLcom/intel/realsense/librealsense/FrameCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Pipeline_nStartWithCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_intel_realsense_librealsense_Pipeline
 * Method:    nStartWithConfig
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Pipeline_nStartWithConfig
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Pipeline
 * Method:    nStartWithConfigAndCallback
 * Signature: (JJLcom/intel/realsense/librealsense/FrameCallback;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Pipeline_nStartWithConfigAndCallback
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_intel_realsense_librealsense_Pipeline
 * Method:    nStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Pipeline_nStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Pipeline
 * Method:    nWaitForFrames
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Pipeline_nWaitForFrames
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
