/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_DepthFrame */

#ifndef _Included_com_intel_realsense_librealsense_DepthFrame
#define _Included_com_intel_realsense_librealsense_DepthFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_DepthFrame
 * Method:    nGetDistance
 * Signature: (JII)F
 */
JNIEXPORT jfloat JNICALL Java_com_intel_realsense_librealsense_DepthFrame_nGetDistance
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_intel_realsense_librealsense_DepthFrame
 * Method:    nGetUnits
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_intel_realsense_librealsense_DepthFrame_nGetUnits
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
