/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_ProcessingBlock */

#ifndef _Included_com_intel_realsense_librealsense_ProcessingBlock
#define _Included_com_intel_realsense_librealsense_ProcessingBlock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_ProcessingBlock
 * Method:    nDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_ProcessingBlock_nDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_ProcessingBlock
 * Method:    nInvoke
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_ProcessingBlock_nInvoke
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
