/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_FwLogMsg */

#ifndef _Included_com_intel_realsense_librealsense_FwLogMsg
#define _Included_com_intel_realsense_librealsense_FwLogMsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_FwLogMsg
 * Method:    nRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_FwLogMsg_nRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogMsg
 * Method:    nGetSeverity
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_FwLogMsg_nGetSeverity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogMsg
 * Method:    nGetSeverityStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_realsense_librealsense_FwLogMsg_nGetSeverityStr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogMsg
 * Method:    nGetTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FwLogMsg_nGetTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogMsg
 * Method:    nGetData
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_intel_realsense_librealsense_FwLogMsg_nGetData
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_intel_realsense_librealsense_FwLogMsg
 * Method:    nGetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_FwLogMsg_nGetSize
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
