/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_RoiSensor */

#ifndef _Included_com_intel_realsense_librealsense_RoiSensor
#define _Included_com_intel_realsense_librealsense_RoiSensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_RoiSensor
 * Method:    nSetRegionOfInterest
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_RoiSensor_nSetRegionOfInterest
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_intel_realsense_librealsense_RoiSensor
 * Method:    nGetRegionOfInterest
 * Signature: (JLcom/intel/realsense/librealsense/RegionOfInterest;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_RoiSensor_nGetRegionOfInterest
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
