/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_MotionStreamProfile */

#ifndef _Included_com_intel_realsense_librealsense_MotionStreamProfile
#define _Included_com_intel_realsense_librealsense_MotionStreamProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_MotionStreamProfile
 * Method:    nGetIntrinsic
 * Signature: (JLcom/intel/realsense/librealsense/MotionIntrinsic;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_MotionStreamProfile_nGetIntrinsic
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
