/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_ThresholdFilter */

#ifndef _Included_com_intel_realsense_librealsense_ThresholdFilter
#define _Included_com_intel_realsense_librealsense_ThresholdFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_ThresholdFilter
 * Method:    nCreate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_ThresholdFilter_nCreate
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
