/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_Align */

#ifndef _Included_com_intel_realsense_librealsense_Align
#define _Included_com_intel_realsense_librealsense_Align
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_Align
 * Method:    nCreate
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Align_nCreate
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
