/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_StreamProfile */

#ifndef _Included_com_intel_realsense_librealsense_StreamProfile
#define _Included_com_intel_realsense_librealsense_StreamProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_StreamProfile
 * Method:    nIsProfileExtendableTo
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_realsense_librealsense_StreamProfile_nIsProfileExtendableTo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_StreamProfile
 * Method:    nGetProfile
 * Signature: (JLcom/intel/realsense/librealsense/StreamProfile/ProfileParams;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_StreamProfile_nGetProfile
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_intel_realsense_librealsense_StreamProfile
 * Method:    nDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_StreamProfile_nDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_StreamProfile
 * Method:    nGetExtrinsicTo
 * Signature: (JJLcom/intel/realsense/librealsense/Extrinsic;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_StreamProfile_nGetExtrinsicTo
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_intel_realsense_librealsense_StreamProfile
 * Method:    nRegisterExtrinsic
 * Signature: (JJLcom/intel/realsense/librealsense/Extrinsic;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_StreamProfile_nRegisterExtrinsic
  (JNIEnv *, jclass, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
