/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_Utils */

#ifndef _Included_com_intel_realsense_librealsense_Utils
#define _Included_com_intel_realsense_librealsense_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_Utils
 * Method:    nProjectPointToPixel
 * Signature: (Lcom/intel/realsense/librealsense/Pixel;Lcom/intel/realsense/librealsense/Intrinsic;Lcom/intel/realsense/librealsense/Point_3D;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Utils_nProjectPointToPixel
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_intel_realsense_librealsense_Utils
 * Method:    nDeprojectPixelToPoint
 * Signature: (Lcom/intel/realsense/librealsense/Point_3D;Lcom/intel/realsense/librealsense/Intrinsic;Lcom/intel/realsense/librealsense/Pixel;F)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Utils_nDeprojectPixelToPoint
  (JNIEnv *, jclass, jobject, jobject, jobject, jfloat);

/*
 * Class:     com_intel_realsense_librealsense_Utils
 * Method:    nTransformPointToPoint
 * Signature: (Lcom/intel/realsense/librealsense/Point_3D;Lcom/intel/realsense/librealsense/Extrinsic;Lcom/intel/realsense/librealsense/Point_3D;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Utils_nTransformPointToPoint
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_intel_realsense_librealsense_Utils
 * Method:    nGetFov
 * Signature: (Lcom/intel/realsense/librealsense/Utils/Fov;Lcom/intel/realsense/librealsense/Intrinsic;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Utils_nGetFov
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_intel_realsense_librealsense_Utils
 * Method:    nProject2dPixelToDepthPixel
 * Signature: (Lcom/intel/realsense/librealsense/Pixel;JFFFLcom/intel/realsense/librealsense/Intrinsic;Lcom/intel/realsense/librealsense/Intrinsic;Lcom/intel/realsense/librealsense/Extrinsic;Lcom/intel/realsense/librealsense/Extrinsic;Lcom/intel/realsense/librealsense/Pixel;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Utils_nProject2dPixelToDepthPixel
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
