/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_VideoStreamProfile */

#ifndef _Included_com_intel_realsense_librealsense_VideoStreamProfile
#define _Included_com_intel_realsense_librealsense_VideoStreamProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_VideoStreamProfile
 * Method:    nGetResolution
 * Signature: (JLcom/intel/realsense/librealsense/VideoStreamProfile/ResolutionParams;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_VideoStreamProfile_nGetResolution
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_intel_realsense_librealsense_VideoStreamProfile
 * Method:    nGetIntrinsic
 * Signature: (JLcom/intel/realsense/librealsense/Intrinsic;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_VideoStreamProfile_nGetIntrinsic
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
