/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_Options */

#ifndef _Included_com_intel_realsense_librealsense_Options
#define _Included_com_intel_realsense_librealsense_Options
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_Options
 * Method:    nSupports
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_realsense_librealsense_Options_nSupports
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_Options
 * Method:    nGetValue
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_intel_realsense_librealsense_Options_nGetValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_Options
 * Method:    nSetValue
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Options_nSetValue
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     com_intel_realsense_librealsense_Options
 * Method:    nGetRange
 * Signature: (JILcom/intel/realsense/librealsense/Options/OptionRange;)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Options_nGetRange
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_intel_realsense_librealsense_Options
 * Method:    nIsReadOnly
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_realsense_librealsense_Options_nIsReadOnly
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_Options
 * Method:    nGetDescription
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_realsense_librealsense_Options_nGetDescription
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_Options
 * Method:    nGetValueDescription
 * Signature: (JIF)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_realsense_librealsense_Options_nGetValueDescription
  (JNIEnv *, jclass, jlong, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
