/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_Frame */

#ifndef _Included_com_intel_realsense_librealsense_Frame
#define _Included_com_intel_realsense_librealsense_Frame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nIsFrameExtendableTo
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_realsense_librealsense_Frame_nIsFrameExtendableTo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nAddRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Frame_nAddRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Frame_nRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nGetStreamProfile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Frame_nGetStreamProfile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nGetDataSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_Frame_nGetDataSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nGetData
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_Frame_nGetData
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nGetNumber
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_Frame_nGetNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nGetTimestamp
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_intel_realsense_librealsense_Frame_nGetTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nGetTimestampDomain
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_Frame_nGetTimestampDomain
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nGetMetadata
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_Frame_nGetMetadata
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_Frame
 * Method:    nSupportsMetadata
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_realsense_librealsense_Frame_nSupportsMetadata
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
