/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_DepthSensor */

#ifndef _Included_com_intel_realsense_librealsense_DepthSensor
#define _Included_com_intel_realsense_librealsense_DepthSensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_DepthSensor
 * Method:    nGetDepthScale
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_intel_realsense_librealsense_DepthSensor_nGetDepthScale
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
