/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_FrameQueue */

#ifndef _Included_com_intel_realsense_librealsense_FrameQueue
#define _Included_com_intel_realsense_librealsense_FrameQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_FrameQueue
 * Method:    nCreate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FrameQueue_nCreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_intel_realsense_librealsense_FrameQueue
 * Method:    nDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_FrameQueue_nDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FrameQueue
 * Method:    nPollForFrame
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FrameQueue_nPollForFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FrameQueue
 * Method:    nWaitForFrames
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FrameQueue_nWaitForFrames
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_FrameQueue
 * Method:    nEnqueue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_FrameQueue_nEnqueue
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
