/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_FwLogParsedMsg */

#ifndef _Included_com_intel_realsense_librealsense_FwLogParsedMsg
#define _Included_com_intel_realsense_librealsense_FwLogParsedMsg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_FwLogParsedMsg
 * Method:    nRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_FwLogParsedMsg_nRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogParsedMsg
 * Method:    nGetMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_realsense_librealsense_FwLogParsedMsg_nGetMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogParsedMsg
 * Method:    nGetFileName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_realsense_librealsense_FwLogParsedMsg_nGetFileName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogParsedMsg
 * Method:    nGetThreadName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_realsense_librealsense_FwLogParsedMsg_nGetThreadName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogParsedMsg
 * Method:    nGetSeverity
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_realsense_librealsense_FwLogParsedMsg_nGetSeverity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogParsedMsg
 * Method:    nGetLine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_FwLogParsedMsg_nGetLine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogParsedMsg
 * Method:    nGetTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_FwLogParsedMsg_nGetTimestamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_FwLogParsedMsg
 * Method:    nGetSequenceId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_FwLogParsedMsg_nGetSequenceId
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
