/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_RsContext */

#ifndef _Included_com_intel_realsense_librealsense_RsContext
#define _Included_com_intel_realsense_librealsense_RsContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_RsContext
 * Method:    nCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_RsContext_nCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_realsense_librealsense_RsContext
 * Method:    nGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_intel_realsense_librealsense_RsContext_nGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_intel_realsense_librealsense_RsContext
 * Method:    nQueryDevices
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_realsense_librealsense_RsContext_nQueryDevices
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_intel_realsense_librealsense_RsContext
 * Method:    nDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_intel_realsense_librealsense_RsContext_nDelete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
