/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_realsense_librealsense_VideoFrame */

#ifndef _Included_com_intel_realsense_librealsense_VideoFrame
#define _Included_com_intel_realsense_librealsense_VideoFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_realsense_librealsense_VideoFrame
 * Method:    nGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_VideoFrame_nGetWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_VideoFrame
 * Method:    nGetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_VideoFrame_nGetHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_VideoFrame
 * Method:    nGetStride
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_VideoFrame_nGetStride
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_intel_realsense_librealsense_VideoFrame
 * Method:    nGetBitsPerPixel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_intel_realsense_librealsense_VideoFrame_nGetBitsPerPixel
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
